---
title: 7 Families
timezone: UTC
collections:
  families:
    title: Families
    output: true
    permalink: "/:path-family"
    defaults:
    - values:
        layout: family
  posts:
    title: Posts
    output: true
  timelines:
    title: Timelines
    output: true
    permalink: "/:path-timeline"
    defaults:
    - values:
        layout: timeline
        events: 
  uploads:
    title: Uploads
    output: true
news:
  title: ITV meets the Clarke Family
  text: ITV’s Divya Kohli meets with Tracey Clarke and husband Tim, to see how their
    lives have been affected through Tracey’s loss of sight and how 7 Families has
    helped them throughout 2015.
  image: "/uploads/img_itv-news-clarke-family.jpg"
  linktext: View the Clarke Family video on ITV
  link: http://www.itv.com/news/meridian/2015-11-19/too-ill-to-earn-charity-warns-of-protecting-our-income/
game:
  title: How Finvincible are you?
  body: |-
    Ever wondered what might be the outcome if something happened that prevented you from working?..... A sudden accident or a serious health problem.  Are you financially invincible? Take our quick test to see how #finvincible you really are!

    Take the 7 Families quiz on Facebook now.
  linktext: Play Now
  link: https://apps.facebook.com/sevenfamilies/
